version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
    volumes:
      - .:/app
    command: php artisan serve --host=0.0.0.0 --port=8080
    # environment:
    #   - APP_ENV=local
    #   - APP_DEBUG=true
    #   - CACHE_DRIVER=redis
    #   - QUEUE_CONNECTION=redis
    #   - REDIS_HOST=redis
    #   - DB_CONNECTION=mysql
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_DATABASE=blog-api
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root_password
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blog-api
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: rediss
    ports:
      - "6379:6379"

volumes:
  dbdata:
